spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ratheesh@123
    url: jdbc:mysql://localhost:3306/sbms27
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    
    
    
    
    
  